<?php
/**
 * Generates llm.txt file for AI crawlers and LLMs.
 *
 * @package SamanLabs\SEO
 */

namespace SamanLabs\SEO\Service;

defined( 'ABSPATH' ) || exit;

/**
 * LLM.txt generator.
 */
class LLM_TXT_Generator {

	/**
	 * Boot hooks.
	 *
	 * @return void
	 */
	public function boot() {
		if ( '1' !== get_option( 'wpseopilot_enable_llm_txt', '0' ) ) {
			return;
		}

		if ( ! apply_filters( 'wpseopilot_feature_toggle', true, 'llm_txt' ) ) {
			return;
		}

		add_action( 'init', [ $this, 'register_rewrite_rules' ] );
		add_action( 'template_redirect', [ $this, 'render_llm_txt' ], 0 );
	}

	/**
	 * Register rewrite rules for llm.txt.
	 *
	 * @return void
	 */
	public function register_rewrite_rules() {
		add_rewrite_rule( '^llm\.txt$', 'index.php?wpseopilot_llm_txt=1', 'top' );
		add_rewrite_tag( '%wpseopilot_llm_txt%', '1' );
	}

	/**
	 * Render llm.txt file.
	 *
	 * @return void
	 */
	public function render_llm_txt() {
		if ( ! get_query_var( 'wpseopilot_llm_txt' ) ) {
			return;
		}

		$content = $this->generate_llm_txt_content();

		nocache_headers();
		header( 'Content-Type: text/plain; charset=UTF-8' );

		echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped

		exit;
	}

	/**
	 * Generate the llm.txt content.
	 *
	 * @return string
	 */
	private function generate_llm_txt_content() {
		$output = [];

		// Header
		if ( ! function_exists( 'get_plugin_data' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}

		$plugin_info = get_plugin_data( SAMANLABS_SEO_PATH . 'wp-seo-pilot.php', false, false );
		$plugin_version = $plugin_info['Version'] ?? SAMANLABS_SEO_VERSION;

		$output[] = sprintf(
			'Generated by %s v%s, this is an llms.txt file, used by LLMs to index the site.',
			get_bloginfo( 'name' ),
			$plugin_version
		);
		$output[] = '';

		// Site title and description
		$custom_title = get_option( 'wpseopilot_llm_txt_title', '' );
		$title = ! empty( $custom_title ) ? $custom_title : get_bloginfo( 'name' );
		$output[] = '# ' . $title;

		$custom_description = get_option( 'wpseopilot_llm_txt_description', '' );
		$description = ! empty( $custom_description ) ? $custom_description : get_bloginfo( 'description' );
		if ( $description ) {
			$output[] = '';
			$output[] = $description;
		}
		$output[] = '';

		// Sitemaps section
		$output[] = '## Sitemaps';
		$output[] = '';

		// Add sitemap if enabled
		if ( '1' === get_option( 'wpseopilot_enable_sitemap_enhancer', '0' ) ) {
			$output[] = '- [XML Sitemap](' . home_url( '/sitemap_index.xml' ) . '): Contains all public & indexable URLs for this website.';
		} else {
			// Fallback to WordPress core sitemap
			$output[] = '- [XML Sitemap](' . home_url( '/wp-sitemap.xml' ) . '): Contains all public & indexable URLs for this website.';
		}
		$output[] = '';

		// Get post types
		$post_types = get_post_types(
			[
				'public'  => true,
				'show_ui' => true,
			],
			'objects'
		);

		unset( $post_types['attachment'] );

		$posts_per_type = absint( get_option( 'wpseopilot_llm_txt_posts_per_type', 50 ) );
		$posts_per_type = max( 1, min( 500, $posts_per_type ) ); // Clamp between 1 and 500

		$include_excerpt = get_option( 'wpseopilot_llm_txt_include_excerpt', '1' );

		// Generate sections for each post type
		foreach ( $post_types as $post_type ) {
			$posts = get_posts(
				[
					'post_type'      => $post_type->name,
					'posts_per_page' => $posts_per_type,
					'post_status'    => 'publish',
					'orderby'        => 'date',
					'order'          => 'DESC',
				]
			);

			if ( empty( $posts ) ) {
				continue;
			}

			$output[] = '## ' . $post_type->label;
			$output[] = '';

			foreach ( $posts as $post ) {
				$title = get_the_title( $post );
				$url   = get_permalink( $post );

				// Get excerpt or meta description if enabled
				$description = '';
				if ( '1' === $include_excerpt ) {
					$meta_desc = get_post_meta( $post->ID, '_wpseopilot_meta_description', true );

					if ( $meta_desc ) {
						$description = ' - ' . wp_trim_words( $meta_desc, 20, '...' );
					} elseif ( has_excerpt( $post ) ) {
						$description = ' - ' . wp_trim_words( get_the_excerpt( $post ), 20, '...' );
					}
				}

				$output[] = '- [' . esc_html( $title ) . '](' . esc_url( $url ) . ')' . esc_html( $description );
			}

			$output[] = '';
		}

		/**
		 * Filter the generated llm.txt content.
		 *
		 * @param array $output Array of lines to be joined.
		 */
		$output = apply_filters( 'wpseopilot_llm_txt_content', $output );

		return implode( "\n", $output );
	}
}
